### ISSUE TITLE
Slurm behavior changes as of ARC Summer 2023 Maintenance

### ISSUE THREAD

**Issue by cb-42** [piyuranjan/DicksonLabScripts#4]
Heads up - it looks like `SLURM_CPUS_PER_TASK` will need to be updated to `SRUN_CPUS_PER_TASK` in the mothurGreatLakes.sh scripts, unless there's a different solution/rework that would be preferred. There's a note about this Slurm change on the [ARC Summer 2023 Maintenance page](https://arc.umich.edu/summer-2023-maintenance/).

**Comment by piyuranjan** [comment]
Thanks for noticing this, @cb-42. From ARC's documentation, it seems that SLURM is now making the call for number of CPUs explicit by deprecating the `SLURM_CPUS_PER_TASK` environment var. We already call the [mothurGreatLakes.sh](https://github.com/piyuranjan/DicksonLabScripts/blob/main/mothurGreatLakes.sh) with an explicit `#SBATCH --cpus-per-task=10`, so we should not see any change.
Let me know if it doesn't work after the summer maintenance and I will adjust the script accordingly.
